"Traditional"
Gofer new
	squeaksource: 'Seaside30';
	package: 'Seaside-Examples';
	load.
!
"Development and Admin Tools"
Gofer new
	squeaksource: 'Seaside30';
	package: 'Grease-Slime';
	package: 'Seaside-Slime';
	package: 'Seaside-Tools-OmniBrowser';
	package: 'Seaside-Pharo-Tools-OmniBrowser';
	load.
!
"RSS"
Gofer new
	squeaksource: 'Seaside30';
	package: 'RSS-Examples';
	load.
!
"Javascript"
Gofer new
	squeaksource: 'Seaside30';
	package: 'Comet-Examples';
	load.
!
"Other Packages"
Gofer new
	squeaksource: 'Seaside30';
	package: 'Seaside-Welcome';
	package: 'Seaside-Pharo-Welcome';
	load.
