Transcript crShow: 'Traditional'.
Gofer new
	squeaksource: 'Seaside30';
	package: 'Seaside-Examples';
	load.
!
Transcript crShow: 'Development and Admin Tools'.
Gofer new
	squeaksource: 'Seaside30';
	package: 'Grease-Slime';
	package: 'Seaside-Slime';
	package: 'Seaside-Tools-OmniBrowser';
	package: 'Seaside-Pharo-Tools-OmniBrowser';
	load.
!
Transcript crShow: 'RSS'.
Gofer new
	squeaksource: 'Seaside30';
	package: 'RSS-Examples';
	load.
!
Transcript crShow: 'Javascript'.
Gofer new
	squeaksource: 'Seaside30';
	package: 'Comet-Examples';
	load.
!
Transcript crShow: 'Other Packages'.
Gofer new
	squeaksource: 'Seaside30';
	package: 'Seaside-Welcome';
	package: 'Seaside-Pharo-Welcome';
	load.
