Transcript show: 'Traditional'; cr.
Gofer new
	squeaksource: 'Seaside30';
	package: 'Seaside-Examples';
	load.
!
Transcript show: 'Development and Admin Tools'; cr.
Gofer new
	squeaksource: 'Seaside30';
	package: 'Grease-Slime';
	package: 'Seaside-Slime';
	package: 'Seaside-Tools-OmniBrowser';
	package: 'Seaside-Pharo-Tools-OmniBrowser';
	load.
!
Transcript show: 'RSS'; cr.
Gofer new
	squeaksource: 'Seaside30';
	package: 'RSS-Examples';
	load.
!
Transcript show: 'Javascript'; cr.
Gofer new
	squeaksource: 'Seaside30';
	package: 'Comet-Examples';
	load.
!
Transcript show: 'Other Packages'; cr.
Gofer new
	squeaksource: 'Seaside30';
	package: 'Seaside-Welcome';
	package: 'Seaside-Pharo-Welcome';
	load.
